version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@expo/webpack-config"
    versions:
    - 0.12.56
    - 0.12.57
    - 0.12.58
    - 0.12.59
    - 0.12.60
    - 0.12.61
    - 0.12.62
    - 0.12.63
    - 0.12.64
    - 0.12.65
    - 0.12.66
    - 0.12.68
  - dependency-name: expo-cli
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.1.6
    - 4.2.1
    - 4.3.0
    - 4.3.1
    - 4.3.2
    - 4.3.4
    - 4.3.5
    - 4.4.1
    - 4.4.3
  - dependency-name: expo
    versions:
    - 40.0.1
    - 41.0.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: flow-bin
    versions:
    - 0.143.1
    - 0.144.0
    - 0.145.0
    - 0.146.0
    - 0.147.0
    - 0.148.0
  - dependency-name: styled-components
    versions:
    - 5.2.1
    - 5.2.2
  - dependency-name: "@types/react-native"
    versions:
    - 0.63.46
    - 0.63.47
    - 0.63.48
    - 0.63.49
    - 0.63.50
    - 0.63.51
    - 0.63.52
    - 0.64.0
    - 0.64.2
  - dependency-name: react-native-reanimated
    versions:
    - 1.13.2
    - 2.0.0
    - 2.0.1
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.18
    - 7.12.5
    - 7.13.10
    - 7.13.2
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: "@welldone-software/why-did-you-render"
    versions:
    - 6.0.5
    - 6.1.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: react-native-gesture-handler
    versions:
    - 1.10.0
    - 1.10.1
    - 1.10.2
    - 1.9.0
  - dependency-name: "@react-navigation/stack"
    versions:
    - 5.14.2
    - 5.14.3
  - dependency-name: react-native-web
    versions:
    - 0.14.10
    - 0.14.11
    - 0.14.12
  - dependency-name: react-native-code-push
    versions:
    - 7.0.0
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: appcenter
    versions:
    - 4.0.2
  - dependency-name: react-native
    versions:
    - 0.63.4
  - dependency-name: react-navigation
    versions:
    - 4.4.3
  - dependency-name: flow-typed
    versions:
    - 3.2.1
  - dependency-name: lodash
    versions:
    - 4.17.20
